version: '3'

services:
  database:
    image: 'mysql:8.0'
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: main
    ports:
      - '3307:3306'
  redis:
    image: redis:7.0.0
    ports:
      - 12345:6379
volumes:
  database_data:
